#Database properties:
db.system: dameng
db.driver: dm.jdbc.driver.DmDriver

instances:
  - db.address: 1.2.3.4
    db.port: 5236
    db.username: SYSDBA
    db.password: VXMzcnBhODgq
    db.connection.url: jdbc:dm://1.2.3.4:5236
    db.name: myDB1

    #Data collector properties:
    poll.interval: 30
    callback.interval: 20
    otel.backend.url: http://127.0.0.1:4317

    #OTel properties:
    otel.service.name: DamengDC1

  - db.address: 1.2.3.4
    db.port: 5236
    db.username: SYSDBA
    db.password: VXMzcnBhODgq
    db.connection.url: jdbc:dm://1.2.3.4:5236
    db.name: myDB2

    #Data collector properties:
    poll.interval: 30
    callback.interval: 20
    otel.backend.url: http://127.0.0.1:4317

    #OTel properties:
    otel.service.name: DamengDC2

